# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_vaes',
                'doc_host': 'https://AbdullhRtima.github.io',
                'git_url': 'https://github.com/AbdullhRtima/nbdev_vaes',
                'lib_path': 'nbdev_vaes'},
  'syms': {'nbdev_vaes.core': {'nbdev_vaes.core.get_sum': ('core.html#get_sum', 'nbdev_vaes/core.py')}}}
